name: Black formatter 2
on: [push, pull_request]

jobs:
  linter_name:
    permissions: write-all
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Installing black formatter
        run: pip install black
      - name: Check using black
        run: black . --check --verbose
      - name: Annotate diff changes using reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
